[package]
name = "solaris-example"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]

[dependencies]
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
ethabi-derive = { git = "https://github.com/tomusdrw/ethabi.git"}
ethabi-contract = { git = "https://github.com/tomusdrw/ethabi.git"}
solaris = { path = "../solaris", version = "0.1" }
ethereum-types = { git = "https://github.com/paritytech/primitives.git" }
rustc-hex = "1.0"

[build-dependencies]
solc = { path = "../solc", version = "0.1" }
