[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]

[dependencies]
ethabi = { git = "https://github.com/paritytech/ethabi.git" }
ethcore = { git = "https://github.com/paritytech/parity.git" }
ethcore-transaction = { git = "https://github.com/paritytech/parity.git" }
ethcore-bytes = { git = "https://github.com/paritytech/parity.git" }
ethereum-types = "0.3"
evm = { git = "https://github.com/paritytech/parity.git" }
lazy_static = "0.2"
vm = { git = "https://github.com/paritytech/parity.git" }
error-chain = "0.11.0"
